server:
  port: 8002

spring:
  application:
    name: login-service
  cloud:
    nacos:
      server-addr: 192.168.1.27:8848
      discovery:
        namespace: TEST

  datasource:
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/zy_thing?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000


mybatis-plus:
  type-aliases-package: com.example.commonutils.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  protocol:
    # 使用 dubbo 协议
    name: dubbo
    # 这个dubbo的协议端口在一台服务器上的时候，每个项目的必须配置成不一样的（否则将启动失败），或者配置为-1，使用随机端口
    port: -1
  registry:
    # 目前使用的是 nacos ， 所以使用 nacos 的协议
    address: nacos://127.0.0.1:8848
  scan:
    # 配置需要扫描的注解包
    base-packages: com.example.loginserviceone
#
#
#seata:
#  # 注册中心配置
#  registry:
#    # 修改注册类型，这里需要根据实际情况修改
#    type: nacos
#    nacos:
#      application: seata-server #默认值
#      username: nacos   # 默认值
#      password: nacos   # 默认值
#      group: SEATA_GROUP # 默认 SEATA_GROUP
#      cluster: default  # 默认 default
#      server-addr: 127.0.0.1:8848
#
#  # 配置中心的配置
#  config:
#    type: nacos
#    nacos:
#      username: nacos
#      password: nacos
#      group: SEATA_GROUP
#      server-addr: 127.0.0.1:8848
#
#  # 事务分组，看 config.txt
#  tx-service-group: my_test_tx_group